server:
  port: {SERVER_PORT: 8080}

mongodb:
  dbname: {DBNAME: "zielke-mongodb"}
  dbcollections:
    pessoas: {DBCOLLECTION: "pessoas"}
  dbuser: {DBUSER: "zielke"}
  dbpassword: {DBPWD: "123"}
  dbhost: ${DBHOST}