version: '3.5'

services:
  db:
    # Banco de dados
    image: mongo
    container_name: zielke-mongodb
    environment:
      MONGO_INITDB_DATABASE: "zielke_mongodb"
      MONGO_INITDB_ROOT_USERNAME: "zielke"
      MONGO_INITDB_ROOT_PASSWORD: "123"
    ports:
      - "1211:27017"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.0GB'
  api1:
    # API - Instância 01
    image: eduardozielke/rinha-backend  
    container_name: api1
    hostname: api1
    depends_on:
      - db
    expose:
      - "1212"
    environment:
      DB_HOST: db
      DB_NAME: "zielke_mongodb"
      DB_USER: "zielke"
      DB_PWD: "123"
      DB_COLLECTION: "pessoas"
      SERVER_PORT: 8080
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.85GB'

  api2:
    # API - Instância 01
    image: eduardozielke/rinha-backend    
    container_name: api2
    hostname: api2
    depends_on:
      - db
    expose:
      - "1313"
    environment:
      DB_HOST: db
      DB_NAME: "zielke_mongodb"
      DB_USER: "zielke"
      DB_PWD: "123"
      DB_COLLECTION: "pessoas"
      SERVER_PORT: 8080
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.85GB'

  nginx:
    # Load Balancer
    image: nginx:latest
    container_name: nginx-rinha
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
